target: assert getpid pointer cast print_str strlen
	gcc -Wall -o assert assert.c
	gcc -Wall -o pointer pointer.c
	gcc -Wall -o getpid getpid.c
	gcc -Wall -o cast cast.c
	gcc -Wall -o print_str print_str.c
	gcc -Wall -o strlen strlen.c
clean:
	rm -rf assert getpid pointer cast print_str strlen
